package shortcutHelper.backend.functionality.setStorageOnTheFlyFunctionality;
	
public abstract class AbstractSetStorageOnTheFlyFunctionalityDataContainerDataExtractor implements ISetStorageOnTheFlyFunctionalityDataContainerDataExtractor{
		
}
