package shortcutHelper.backend.functionality.setStorageOnTheFlyFunctionality;

import shortcutHelper.backend.functionality.AbstractFunctionalityDataContainerCreator;

public abstract class AbstractSetStorageOnTheFlyFunctionalityDataContainerCreator extends AbstractFunctionalityDataContainerCreator implements ISetStorageOnTheFlyFunctionalityDataContainerCreator{
	
};
