connections: 
 - 
  name: pitabeauty
  host: localhost
  port: 3306
  username: root
  password: root
  database: PitabeautyDev
 - 
  name: another
  port: 3306
  username: root
  password: root
  database: PitabeautyDev
