package shortcutHelper.backend.functionality.selectQueryDatabaseFunctionality;
	
public abstract class AbstractSelectQueryDatabaseFunctionalityDataContainerDataExtractor implements ISelectQueryDatabaseFunctionalityDataContainerDataExtractor{
		
}
